export const defaultRuleWeights = [
  {
    id: '1',
    category: 'course',
    name: '课程连续性',
    description: '同一课程尽量安排在连续时段',
    defaultWeight: 20,
    currentWeight: 20,
    minWeight: 0,
    maxWeight: 30,
    enabled: true,
  },
  {
    id: '2',
    category: 'course',
    name: '课程难度分布',
    description: '高难度课程不宜集中在同一天',
    defaultWeight: 15,
    currentWeight: 15,
    minWeight: 0,
    maxWeight: 25,
    enabled: true,
  },
  {
    id: '3',
    category: 'teacher',
    name: '教师时间偏好',
    description: '满足教师对授课时间段的偏好',
    defaultWeight: 18,
    currentWeight: 18,
    minWeight: 0,
    maxWeight: 25,
    enabled: true,
  },
  {
    id: '4',
    category: 'teacher',
    name: '教师工作强度均衡',
    description: '避免教师单日授课过多',
    defaultWeight: 12,
    currentWeight: 12,
    minWeight: 0,
    maxWeight: 20,
    enabled: true,
  },
  {
    id: '5',
    category: 'time',
    name: '黄金时段分配',
    description: '重要课程安排在上午黄金时段',
    defaultWeight: 15,
    currentWeight: 15,
    minWeight: 0,
    maxWeight: 25,
    enabled: true,
  },
  {
    id: '6',
    category: 'time',
    name: '课程时段分布',
    description: '理论课和实践课时段合理分布',
    defaultWeight: 10,
    currentWeight: 10,
    minWeight: 0,
    maxWeight: 20,
    enabled: true,
  },
  {
    id: '7',
    category: 'resource',
    name: '教室使用效率',
    description: '提高教室使用率，避免空置',
    defaultWeight: 8,
    currentWeight: 8,
    minWeight: 0,
    maxWeight: 15,
    enabled: true,
  },
  {
    id: '8',
    category: 'resource',
    name: '专业教室匹配',
    description: '专业课程安排在对应专业教室',
    defaultWeight: 12,
    currentWeight: 12,
    minWeight: 0,
    maxWeight: 20,
    enabled: true,
  },
];
